"""Phase 2 additions

Revision ID: 2585e32222bb
Revises: a27b3a10d786
Create Date: 2026-09-02 13:26:32.068528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '2585e32222bb'
down_revision: Union[str, None] = 'a27b3a10d786'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create the Enum type in PostgreSQL
    indexing_status_enum = sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='indexingstatus')
    indexing_status_enum.create(op.get_bind(), checkfirst=True)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('indexing_status', indexing_status_enum, nullable=False, server_default='PENDING'))
    op.add_column('documents', sa.Column('full_text', sa.Text(), nullable=True))
    op.create_index(op.f('ix_documents_indexing_status'), 'documents', ['indexing_status'], unique=False)
    op.add_column('document_chunks', sa.Column('chunk_type', sa.String(), nullable=True))
    
    # Use explicit raw SQL for altering type from vector(1536) to vector(768) since SQLAlchemy might complain
    op.execute('ALTER TABLE document_chunks ALTER COLUMN embedding TYPE vector(768)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_indexing_status'), table_name='documents')
    op.drop_column('documents', 'full_text')
    op.drop_column('documents', 'indexing_status')
    
    # Drop enum type
    sa.Enum(name='indexingstatus').drop(op.get_bind(), checkfirst=True)
    
    op.execute('ALTER TABLE document_chunks ALTER COLUMN embedding TYPE vector(1536)')
    op.drop_column('document_chunks', 'chunk_type')
    # ### end Alembic commands ###
