"""Add raw_text column

Revision ID: b2786f5c5d85
Revises: 2585e32222bb
Create Date: 2026-09-02 14:33:32.658416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2786f5c5d85'
down_revision: Union[str, None] = '2585e32222bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('raw_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'raw_text')
    # ### end Alembic commands ###
